---
title: "Lab5"
author: "Katelan Fitzgerald"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TIDYVERSE + DPLYR

```{r}
library(tidyverse)
```

```{r, results = "hide"}
Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))

str(Confirmed_State_3_13)

Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))

str(Confirmed_State_9_13)

Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered")

Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13, Confirmed_State_9_13, by = c("Province_State")) %>% 
  rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
  select(-Country_Region.x, -Country_Region.y) %>% 
  replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_3_13_9_13_joined)
which(is.na(Confirmed_State_3_13_9_13_joined))
```

## WIDE TABLE FORMATS
```{r, fig.width = 6, fig.height = 12}
Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>% 
  pivot_longer(-c(Province_State),
               names_to = "Date", values_to = "Confirmed")

view(Confirmed_State_3_13_9_13_joined)
view(Confirmed_State_3_13_9_13_joined_long)

ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_point(aes(color = Date))
```

## TIME SERIES DATA AND LONG FORMAT
```{r}
# downloading confirmed cases

download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", 
               destfile = "data/time_series_covid19_confirmed_global.csv")

time_series_covid19_confirmed_global<- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
head(time_series_covid19_confirmed_global)

time_series_covid19_confirmed_global_long <- time_series_covid19_confirmed_global %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Confirmed")

# downloading deaths

download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")

time_series_covid19_deaths_global <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

time_series_covid19_deaths_global_long <- time_series_covid19_deaths_global %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Deaths")

head(time_series_covid19_deaths_global_long)

# UNITING TIME SERIES TABLES

time_series_covid19_confirmed_global_long <- time_series_covid19_confirmed_global_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = "_", remove = FALSE)
head(time_series_covid19_confirmed_global_long)

time_series_covid19_deaths_global_long <- time_series_covid19_deaths_global_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = "_") %>% 
  select(Key, Deaths)
head(time_series_covid19_deaths_global_long)

# FULL JOIN

time_series_long_joined <- full_join(time_series_covid19_confirmed_global_long, time_series_covid19_deaths_global_long, by = c("Key")) %>% 
  select(-Key)
head(time_series_long_joined)
```

## LUBRIDATE
```{r}
library(lubridate)
```

## MAKING GRAPHS WITH TIME SERIES DATA
```{r}
time_series_long_joined <- full_join(time_series_covid19_confirmed_global_long, time_series_covid19_deaths_global_long, by = c("Key")) %>% 
  select(-Key)
head(time_series_long_joined)

time_series_long_joined$Date <- mdy(time_series_long_joined$Date)

time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)

# US COVID-19 Deaths Plot

time_series_long_joined %>% 
  group_by(Country_Region, Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point((aes(color = Deaths))) +
    geom_line((aes(color = Deaths))) +
    ggtitle("US COVID-19 Deaths")

# Comparing Countries COVID-19 Deaths on Separate Plots

time_series_long_joined %>% 
  group_by(Country_Region, Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South", "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date, y = Deaths)) + 
    geom_point() +
    geom_line((aes(color = "Red"))) +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")

# Comparing Countries COVID-19 Deaths on the Same Plot

time_series_long_joined %>% 
  group_by(Country_Region, Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South", "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date, y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")

# US Confirmed versus Deaths

time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date, y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")

```

## EXERCISES 1-3

```{r, fig.width = 6, fig.height = 12}
Confirmed_State_6_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))
view(Confirmed_State_6_13)

Confirmed_State_6_13 <- Confirmed_State_6_13 %>% 
  filter(Province_State != "Recovered")

Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed))
view(Confirmed_State_9_13)

Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered")

Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
view(Confirmed_State_6_13_9_13_joined)


Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_6_13_2020 = 0))
head(Confirmed_State_6_13_9_13_joined)
view(Confirmed_State_6_13_9_13_joined)

Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")

# make a bar plot for Confirmed_State_6_13_9_13_joined_long
ggplot(data = Confirmed_State_6_13_9_13_joined_long, aes(x = Date, y = Confirmed)) +
  geom_bar(stat = "identity", fill = "Tomato") +
  facet_wrap(vars("Date")) +
  labs(title = "Confirmed US COVID-19 Cases on 6/13/20 and 9/13/20", x = "Date", y = "Number of Confirmed Cases") +
  theme_light() +
  theme(text = element_text (size = 12))

```

## EXERCISES 4-6

```{r, fig.width = 6, fig.height = 12}

view(time_series_long_joined)

# Total confirmed deaths per day
ggplot(data = time_series_long_joined, mapping = aes(x = Date, y = Deaths)) + 
  geom_line(stat = "identity", fill = "None") +
  theme_classic() +
  labs(title = "Covid-19 Global Confirmed Deaths", x = "Date", y = "Daily Confirmed Deaths") +
  theme(plot.title = element_text(hjust = 0.5))
  
view(time_series_covid19_deaths_global_long)

# Deaths/Confirmed Cases
time_series_long_joined$Deaths_to_Confirmed_Ratio <- (time_series_long_joined$Deaths / time_series_long_joined$Confirmed)
view(time_series_long_joined)

time_series_long_joined_us <- time_series_long_joined %>% 
  #select(-Lat, -Long, -Country_Region, -Province_State) %>% 
  group_by(Country_Region, Date) %>% 
  summarize(Deaths_to_Confirmed_Ratio = sum(Deaths_to_Confirmed_Ratio)) %>% 
  filter(Country_Region == "US")
view(time_series_long_joined_us)

# Plot Deaths/Confirmed Cases
n <- time_series_long_joined$Deaths_to_Confirmed_Ratio

ggplot(data = time_series_long_joined_us, mapping = aes(x = Date, y = Deaths_to_Confirmed_Ratio)) + 
  geom_point() +
  labs(title = "Covid-19 Global Deaths to Confirmed Cases Ratio", x = "Date", y = "Deaths/Confirmed")


```
## EXERCISES 7-8
```{r}
# 10 countries with the highest death total
time_series_long_joined_10 <- time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarize(Total_Deaths = sum(Deaths)) %>% 
  arrange(desc(Total_Deaths)) %>%
  slice(1:10)

ggplot(data = time_series_long_joined_10, mapping = aes(x = Country_Region, y = Total_Deaths)) +
  geom_point(stat = "identity") +
  labs(title = "Countries with the Most COVID-19 Deaths", x = "Countries", y = " Total Deaths")


  # Using Facet_Wraps with the plot of countries with the most COVID-19 deaths
ggplot(data = time_series_long_joined_10, mapping = aes(x = Country_Region, y = Total_Deaths)) +
  geom_point(stat = "identity") +
  labs(title = "Countries with the Most COVID-19 Deaths", x = "Countries", y = " Total Deaths") +
  facet_wrap(~Country_Region, ncol = 2)

```

## EXERCISES 9-10
```{r, eval = FALSE}

# Confirmed Cases in US States and Territories
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", 
               destfile = "data/time_series_covid19_confirmed_us.csv")

time_series_covid19_confirmed_us <- read_csv("data/time_series_covid19_confirmed_us.csv")
view(time_series_covid19_confirmed_us)

time_series_covid19_confirmed_us_long <- read_csv("data/time_series_covid19_confirmed_us.csv") %>%
  rename(Long = "Long_") %>% 
  select(-c(UID, iso2, iso3, code3, FIPS)) %>% 
  pivot_longer(-c(Admin2, Province_State, Country_Region, Lat, Long, Combined_Key),
                             names_to = "Date", values_to = "Deaths") %>% 
  ggplot(mapping = aes(x = Country_Region, y = Confirmed)) +
  geom_point(stat = "identity") +
  labs(title = "Confirmed COVID-19 Cases in US States", x = "US States", y = " Confirmed Cases") +
  facet_wrap(~Province_State, ncol = 6)


# Applying a New Theme to Exercise 8
ggplot(data = time_series_long_joined_10, mapping = aes(x = Country_Region, y = Total_Deaths)) +
  geom_point(stat = "identity", aes(color = Country_Region)) +
  theme_light() +
  labs(title = "Countries with the Most COVID-19 Deaths", x = "Countries", y = " Total Deaths") +
  facet_wrap(~Country_Region, ncol = 2)
```

